### ISSUE TITLE
Filesystem case sensitivity

### ISSUE THREAD

**Issue by L2G** [jacksonp/manlib#1]
There is probably not an easy solution, or even a right solution, to this issue.

There are two pairs of files in the man tree where the files have different contents and different names, but when disregarding upper- and lowercase, the filenames are identical:

* [man/man2/_Exit.2](https://github.com/jacksonp/manlib/blob/0c69e3c84d0e72576c7b536dd86570430e1d5ea8/man/man2/_Exit.2) and [man/man2/_exit.2](https://github.com/jacksonp/manlib/blob/0c69e3c84d0e72576c7b536dd86570430e1d5ea8/man/man2/_exit.2)
* [man/man3/NAN.3](https://github.com/jacksonp/manlib/blob/0c69e3c84d0e72576c7b536dd86570430e1d5ea8/man/man3/NAN.3) and [man/man3/nan.3](https://github.com/jacksonp/manlib/blob/0c69e3c84d0e72576c7b536dd86570430e1d5ea8/man/man3/nan.3)

This causes confusion for people (like me :smile_cat:) who clone this Git repo onto a case-insensitive filesystem. It shows up with man/man2/_Exit.2 and man/man3/NAN.3 as dirty in the index. Then after running `git reset --hard`, man/man2/_exit.2 and man/man3/nan.3 show up as dirty. It toggles between those two states.

The only sane workaround I can see is just to make sure that the repo is checked out on a case-sensitive filesystem. Fortunately, this is easy for me to do in Mac OS as I can just make a DMG and use that for case-sensitive work (more trivial to do than converting my whole hard disk!).

**Comment by jacksonp** [comment]
Thanks, I hadn't considered there would be an issue with case-insensitive filesystems. I think you're right, the only thing for it is to use a case-sensitive filesystem.
